[[Xorg_libXinerama]]
arch = "aarch64"
git-tree-sha1 = "b9aae8180169d889b277c61cb8047a351a7abe31"
libc = "glibc"
os = "linux"

    [[Xorg_libXinerama.download]]
    sha256 = "26e8e03ae96c9deb8d835b4e83e843e9f513d6439d01c650857b8ef34d777fd0"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.aarch64-linux-gnu.tar.gz"
[[Xorg_libXinerama]]
arch = "aarch64"
git-tree-sha1 = "e5d64122d630e3e3f9f375981f9ec5b69aff01a0"
libc = "musl"
os = "linux"

    [[Xorg_libXinerama.download]]
    sha256 = "5329aad043f3faf82471eb6799e9323e3e90762557c6e31adb9c5dc6535ed80d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.aarch64-linux-musl.tar.gz"
[[Xorg_libXinerama]]
arch = "aarch64"
git-tree-sha1 = "bc665c6ae4be37a348c3f847a527473c54ffb9e6"
os = "freebsd"

    [[Xorg_libXinerama.download]]
    sha256 = "3f7f1bc72cf9d7e78a0ffe8efd4f20f575338a22f2193a2ba4ac4c4233518588"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXinerama]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b77bb711c24ef91bf47436a46a5449596c684702"
libc = "glibc"
os = "linux"

    [[Xorg_libXinerama.download]]
    sha256 = "898f6beccd49cab849a56aa3344b5e9412df8257814a24163ac08866eeb1d93e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXinerama]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c46247169a6c8668be75ab7bce4c57f1b2b44364"
libc = "musl"
os = "linux"

    [[Xorg_libXinerama.download]]
    sha256 = "7577e32b167e15686ea3add4a387876080f00cc4f7f33875a16b740a9e89012e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXinerama]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f955cd71609dc11977b28e4de14df14175e7c6bd"
libc = "glibc"
os = "linux"

    [[Xorg_libXinerama.download]]
    sha256 = "42fe8434eb53ea1a0e1601f593b030bc4e48c4ced55dcdb7fe4ca7100cc0e7ba"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXinerama]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "174447a22ddd8b2f78ed7500fec8455522c0e008"
libc = "musl"
os = "linux"

    [[Xorg_libXinerama.download]]
    sha256 = "9f0efe3592e9bdc25de6a8dcfd0dbf9f389cdd80c6026d55aff787721cc3ac3f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXinerama]]
arch = "i686"
git-tree-sha1 = "73a050e17eaf8236aa7ffdc44348db80ae844dda"
libc = "glibc"
os = "linux"

    [[Xorg_libXinerama.download]]
    sha256 = "ec797c37def4ac57ae3ae51d4be280dc01cf9afefaf1d867aa18d7a411cdb9fa"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.i686-linux-gnu.tar.gz"
[[Xorg_libXinerama]]
arch = "i686"
git-tree-sha1 = "2286b912aeba66e9b0f36b74928f92a2cfa88406"
libc = "musl"
os = "linux"

    [[Xorg_libXinerama.download]]
    sha256 = "354feefac99c2528e3ce4cce31be166d83efa7597ec250df5df681ca5af51831"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.i686-linux-musl.tar.gz"
[[Xorg_libXinerama]]
arch = "powerpc64le"
git-tree-sha1 = "03b6b9c97f572e99fe59e6e4761746a658829ce4"
libc = "glibc"
os = "linux"

    [[Xorg_libXinerama.download]]
    sha256 = "9b3b0d5f16151f6b5b9361ff5d386743e23544679ae3d0238d36ac4b6c55a746"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXinerama]]
arch = "riscv64"
git-tree-sha1 = "4ec1f5b139aef7dbfb84f142cb4c5c6b88ce922a"
libc = "glibc"
os = "linux"

    [[Xorg_libXinerama.download]]
    sha256 = "b2d308359b187312b3ad42f03ac9ac58419468bc538a427f588b420620ce1ae0"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.riscv64-linux-gnu.tar.gz"
[[Xorg_libXinerama]]
arch = "x86_64"
git-tree-sha1 = "ffa3129185004f04a3849be27d0b7676f5b1af5b"
libc = "glibc"
os = "linux"

    [[Xorg_libXinerama.download]]
    sha256 = "bb96567428dd5c973772bb6bbef5419d5e83457e9802d4e4aeecc20244dfd1b5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.x86_64-linux-gnu.tar.gz"
[[Xorg_libXinerama]]
arch = "x86_64"
git-tree-sha1 = "4f85738e8473d1c1ecd0372e360a937551483b06"
libc = "musl"
os = "linux"

    [[Xorg_libXinerama.download]]
    sha256 = "4582e5449ff806eb8599748cdf00d3482682d6a329a70c0f4efb07992470b65a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.x86_64-linux-musl.tar.gz"
[[Xorg_libXinerama]]
arch = "x86_64"
git-tree-sha1 = "97f3b5f6c7616a3d778b6171c4bb8381852536a1"
os = "freebsd"

    [[Xorg_libXinerama.download]]
    sha256 = "6b6749cc5c7007b5ce7d7e1772f70bcf1992362301819614a4a2a6d9ce344cd3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.7+0/Xorg_libXinerama.v1.1.7.x86_64-unknown-freebsd.tar.gz"
